### ISSUE TITLE
Failing Animator test

### ISSUE THREAD

**Issue by jamesobutler** [SlicerMorph/SlicerMorph#205]
The py_Animator test is failing see https://slicer.cdash.org/test/21921329:

```
======================================================================
ERROR: test_Animator1 (Animator.AnimatorTest)
Ideally you should have several levels of tests.  At the lowest level
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/D/P/S-0-E-b/SlicerMorph-build/lib/Slicer-4.13/qt-scripted-modules/Animator.py", line 1233, in test_Animator1
    logic.addAction(animationNode, roiAction)
  File "D:/D/P/S-0-E-b/SlicerMorph-build/lib/Slicer-4.13/qt-scripted-modules/Animator.py", line 1098, in addAction
    actions[action['id']] = action
TypeError: 'NoneType' object is not subscriptable
```

**Comment by muratmaga** [comment]
Fixed via https://github.com/SlicerMorph/SlicerMorph/commit/8ae3612061356a800dc1ce3fbd62be68185dff25
