### ISSUE TITLE
ALPACA Error "raise LinAlgError("Singular matrix") numpy.linalg.LinAlgError: Singular matrix"

### ISSUE THREAD

**Issue by aConar** [SlicerMorph/SlicerMorph#258]
Dear developers, I'm used ALPACA in the past for landmark for transfer landmark points with success. Now I'm trying to transfer landmark to new specimens but I get the following error message in terminal:

```
:: Loading point clouds and downsampling
:: Downsample with a voxel size 1.896.
:: Estimate normal with search radius 3.793.
:: Compute FPFH feature with search radius 9.482.
:: Downsample with a voxel size 1.896.
:: Estimate normal with search radius 3.793.
:: Compute FPFH feature with search radius 9.482.
:: Loading point clouds and downsampling
:: Downsample with a voxel size 1.896.
:: Estimate normal with search radius 3.793.
:: Compute FPFH feature with search radius 9.482.
:: Downsample with a voxel size 1.896.
:: Estimate normal with search radius 3.793.
:: Compute FPFH feature with search radius 9.482.
:: RANSAC registration on downsampled point clouds.
   Since the downsampling voxel size is 1.896,
   we use a liberal distance threshold 5.689.
Traceback (most recent call last):
  File "/home/ale/Programas/Slicer-5.2.2-linux-amd64/NA-MIC/Extensions-31382/SlicerMorph/lib/Slicer-5.2/qt-scripted-modules/ALPACA.py", line 448, in onRunALPACAButton
    self.transformMatrix = logic.estimateTransform(self.sourcePoints, self.targetPoints, self.sourceFeatures, self.targetFeatures, self.voxelSize, self.ui.skipScalingCheckBox.checked, self.parameterDictionary)
  File "/home/ale/Programas/Slicer-5.2.2-linux-amd64/NA-MIC/Extensions-31382/SlicerMorph/lib/Slicer-5.2/qt-scripted-modules/ALPACA.py", line 1325, in estimateTransform
    ransac = self.execute_global_registration(sourcePoints, targetPoints, sourceFeatures, targetFeatures, voxelSize,
  File "/home/ale/Programas/Slicer-5.2.2-linux-amd64/NA-MIC/Extensions-31382/SlicerMorph/lib/Slicer-5.2/qt-scripted-modules/ALPACA.py", line 1445, in execute_global_registration
    evaluation = registration.evaluate_registration(target_down, source_down, distance_threshold, np.linalg.inv(result.transformation))
  File "<__array_function__ internals>", line 180, in inv
  File "/home/ale/Programas/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 552, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/home/ale/Programas/Slicer-5.2.2-linux-amd64/lib/Python/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 89, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix

```

My system is Ubuntu Jammy 22.04 with Slicer 5.2.2 and Slicermorph cd7dd4c (2023-04-25).

Thanks in advance!

**Comment by muratmaga** [comment]
Singular matrix suggests something funky is going on during decomposition, and it is likely a data specific issue, which we can't replicate without data. Can you share the two model you are trying to transfer the landmarks (and the landmarks of course).

**Comment by muratmaga** [comment]
No way to replicate the issue without sample data. Closing.
