### ISSUE TITLE
GPA - Exclude LM error

### ISSUE THREAD

**Issue by jakublaznovsky** [SlicerMorph/SlicerMorph#276]
Hello Guys,
I encountered an error in the Slicer 5.4.0 version, respectively in the recent GPA module.
It is not possible to run GPA, when I want to exclude some LMs. See the error below - probably related to the updated numpy library

Traceback (most recent call last):
  File "C:/Users/admin/AppData/Local/slicer.org/Slicer 5.4.0/slicer.org/Extensions-31938/SlicerMorph/lib/Slicer-5.4/qt-scripted-modules/GPA.py", line 1220, in onLoad
    self.LMExclusionList=[np.int(x) for x in self.LMExclusionList]
  File "C:/Users/admin/AppData/Local/slicer.org/Slicer 5.4.0/slicer.org/Extensions-31938/SlicerMorph/lib/Slicer-5.4/qt-scripted-modules/GPA.py", line 1220, in <listcomp>
    self.LMExclusionList=[np.int(x) for x in self.LMExclusionList]
  File "C:\Users\admin\AppData\Local\slicer.org\Slicer 5.4.0\lib\Python\Lib\site-packages\numpy\__init__.py", line 313, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Thank you for all the effort!

**Comment by muratmaga** [comment]
Looks like a numpy change that broke it. Thanks for reporting it.

@smeolfe

**Comment by muratmaga** [comment]
@smrolfe
