### ISSUE TITLE
GEVolImport error in preview

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#282]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/maga/Downloads/Slicer-5.5.0-2023-10-10-linux-amd64/lib/Python/lib/python3.9/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/maga/Downloads/Slicer-5.5.0-2023-10-10-linux-amd64/slicer.org/Extensions-32228/SlicerMorph/lib/Slicer-5.5/qt-scripted-modules/GEVolImport.py", line 1, in <module>
    from ctypes import FormatError
ImportError: cannot import name 'FormatError' from 'ctypes' (/home/maga/Downloads/Slicer-5.5.0-2023-10-10-linux-amd64/lib/Python/lib/python3.9/ctypes/__init__.py)
loadSourceAsModule - Failed to load file "/home/maga/Downloads/Slicer-5.5.0-2023-10-10-linux-amd64/slicer.org/Extensions-32228/SlicerMorph/lib/Slicer-5.5/qt-scripted-modules/GEVolImport.py"  as module "GEVolImport" !
Fail to instantiate module  "GEVolImport"
libpng warning: iCCP: profile 'ICC Profile': 'CMYK': invalid ICC profile color space
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: too many profiles
libpng warning: iCCP: known incorrect sRGB profile
The following modules failed to be instantiated:
   GEVolImport

@lassoan

**Comment by lassoan** [comment]
I've pushed a fix, see the referenced pull request.
