### ISSUE TITLE
3D interactive model visualization fails to work once it reports an error about landmark mismatch

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#372]
I have accidentally selected a reference LMs set that was fewer than whats included in the analysis. GPA module nicely reported that this was incorrect. However, when I proceed to load the correct landmark set, it wasn't able to continue. The error log is attached: 

```
"Markups" Reader has successfully read the file "/Users/amaga/Desktop/size_corrected/A_J_Skull.fcsv" "[0.02s]"
Number of landmarks selected for 3D visualization does not match the analysis

"Markups" Reader has successfully read the file "/Users/amaga/Desktop/size_corrected/merged/A_J_Skull_mergedGrid_QSTJ.mrk.json" "[0.03s]"
Traceback (most recent call last):
  File "/Users/amaga/Desktop/Slicer.app/Contents/Extensions-33157/SlicerMorph/lib/Slicer-5.7/qt-scripted-modules/GPA.py", line 1781, in onSelect
    indexToRemove.append(self.LMExclusionList[i]-1)
TypeError: unsupported operand type(s) for -: 'str' and 'int'

```

**Comment by muratmaga** [comment]
Actually I have reset the module and then the scene and proceeded afresh. Error is still there. So I don't think this was anything to do but there is a bug. Not entirely sure why it is trying to remove points from the analysis since there are no missing LMs.  

```Traceback (most recent call last):
  File "/Users/amaga/Desktop/Slicer.app/Contents/Extensions-33157/SlicerMorph/lib/Slicer-5.7/qt-scripted-modules/GPA.py", line 1781, in onSelect
    indexToRemove.append(self.LMExclusionList[i]-1)
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

**Comment by smrolfe** [comment]
I haven't been able to replicate this error. Is it possible there was something in the "Exclude landmarks" field, like a space?

I did notice that once a landmark removed, it requires that number of landmarks to be present in the file loaded for visualization. I can change this so it automatically removes any in the exclude landmark field, if you think it would be useful.

**Comment by muratmaga** [comment]
This definitely reproduces for me when I try on a recent preview on my mac. 
See the PC selectors are not showing anything anymore. I can't go back to the landmark visualization etc...

<img width="535" alt="image" src="https://github.com/user-attachments/assets/0a0d729b-8d1b-4f5c-808f-858278bd8e47" />

**Comment by muratmaga** [comment]
To be more precise, if I go ahead and re-choose the model and the correct LM file, it recovers. But right after the error, GPA module is left in an unusable state.

**Comment by smrolfe** [comment]
I see. To set up the PC sliders for the visualization, it's required that either the 3D model or mean shape option is selected and the "Apply" button is clicked. 

If the 3D model files cannot be loaded, I wouldn't expect the visualization parameters to be active, since the setup failed. I would expect either the user would correct the 3D files loaded, or switch to the mean shape option and hit apply again. 

Aside from the visualization parameters, it looks like the rest of the module is working properly.

**Comment by muratmaga** [comment]
I came there after I set up the visualization for the mean shape (i.e,. landmarks only). After the error the module in an unusuable state (including my mean shape visualization). It would be nice to revert the state before the error, or if not possible then let the user to take action (correct the LM issue or choose a separate visualization method).

**Comment by smrolfe** [comment]
OK! I will revert to the previous state instead of clearing if there is an error.

**Comment by smrolfe** [comment]
It's really strange, I can't seem to get to the same state on my mac. I was using a preview version from 12-10, but also just tried updating to the latest, from 1/13.

Just to clarify, the steps are:
1. Run GPA/PCA
2. Apply 3D visualization setup with mean shape
3. Apply 3D visualization setup with 3D model and landmark set with incorrect number of landmarks
4. Generate and accept error message about the landmark error

After I do these steps, the sliders and visualization I set up for the mean shape are still active. Is it possible this dataset specific?

**Comment by muratmaga** [comment]
what dataset are you using? I am testing with mouse_models repo data. Copy the A/J LM somewhere else and remove the first LM from the file and use it for testing.

**Comment by smrolfe** [comment]
Ok, thanks, I can replicate it with those specimens.

**Comment by smrolfe** [comment]
This update solves the problem for me: https://github.com/SlicerMorph/SlicerMorph/pull/379
