### ISSUE TITLE
check the output folder whether it is writable before commencing the analysis

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/SlicerMorph#45]
If it is, execute the analysis, if not return an error message about not being able to save results (gpa doesn't work properly if can't save).

`Loaded 44 subjects with 500 landmark points.
9
Scale Factor: 0.14121616650561752

Traceback (most recent call last):
  File "/home/maga/.config/NA-MIC/Extensions-28927/SlicerMorph/lib/Slicer-4.11/qt-scripted-modules/GPA.py", line 473, in onLoad
    os.makedirs(self.outputFolder)
  File "/home/maga/Downloads/Slicer-4.11.0-2020-04-03-linux-amd64/bin/../lib/Python/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/kelly/otolith/41clupeiformes_2/auto3dgm_test/l_s_output/phase2/aligned_landmarks/2020-04-24_13_33_45'`

**Comment by smrolfe** [comment]
Added in commit 7ccd6809f4edb078bebae6ac60b8ec59ac4d1569 along with error checking of valid input files.
